PUT http://localhost:3001/api/readinglist/3
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QyQHVzZXIuZGUiLCJpZCI6MiwiaWF0IjoxNjY3NTExNjE2LCJleHAiOjE2Njc1MTUyMTZ9.TROVlVUjDnLRhAh_R3F2I1eBwhgYzlWqa8fiQHyAwQw

{
  "read": true
}