POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RAdXNlci5kZSIsImlkIjoyOSwiaWF0IjoxNjY3NDM4MTE4LCJleHAiOjE2Njc0NDE3MTh9.gmnuap2j0XUCPC90WaIOn0A_-2pq-enzUgz5rjIX-B4

{
    "author": "vscode author",
    "url": "vscode url",
    "title": "vscode title",
    "likes": 9
}

### Test error

POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "author": "testauthor"
}
