POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RAdXNlci5kZSIsImlkIjoxLCJpYXQiOjE2Njc0OTQ0NjcsImV4cCI6MTY2NzQ5ODA2N30.vXgO0wF3Ya98oDkZUcvirVdg9uMpTR52mWFMzxNFTXQ

{
    "author": "vscode author",
    "url": "vscode url",
    "title": "vscode title",
    "likes": 9
}

### Test error

POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "author": "testauthor"
}
