PUT http://localhost:3001/api/persons/6225377d8347e32f3da23a36
content-type: application/json

{
    "name": "added person from vs code",
    "number": "123-123456789"
}


###

PUT https://thawing-coast-07191.herokuapp.com/api/persons/6225377d8347e32f3da23a36
content-type: application/json

{
    "name": "added person from vs code",
    "number": "123-123456789"
}