POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "test person"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "123-123456789"
}
###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "test person",
    "number": "123"
}
###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "test person",
    "number": "1234567890"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "test person",
    "number": "123-123456789"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "test person",
    "number": "123-123456789"
}

###



POST https://thawing-coast-07191.herokuapp.com/api/persons
Content-Type: application/json

{
    "name": "test person"
}

###

POST https://thawing-coast-07191.herokuapp.com/api/persons
Content-Type: application/json

{
    "number": "123-123456789"
}


###

POST https://thawing-coast-07191.herokuapp.com/api/persons
Content-Type: application/json

{
    "name": "test person",
    "number": "123"
}


###

POST https://thawing-coast-07191.herokuapp.com/api/persons
Content-Type: application/json

{
    "name": "test person",
    "number": "1234567890"
}


###

POST https://thawing-coast-07191.herokuapp.com/api/persons
Content-Type: application/json

{
    "name": "test person",
    "number": "123-123456789"
}

###

POST https://thawing-coast-07191.herokuapp.com/api/persons
Content-Type: application/json

{
    "name": "test person",
    "number": "123-123456789"
}